/*!
This module provides an implementation of ISO 639-2, Codes for the
representation of names of languages — Part 2: Alpha-3 code.
 */

// ------------------------------------------------------------------------------------------------
//
// The rest of this file is generated by the package build script.
//
// ------------------------------------------------------------------------------------------------

include!(concat!(env!("OUT_DIR"), "/part_2.rs"));
