/*!
This module provides an implementation of ISO 639-2, Codes for the
representation of names of languages — Part 2: Alpha-3 code.
 */

#[cfg(test)]
mod tests {
    use crate::{part_2::LanguageCode, LanguageCodeError};
    use std::str::FromStr;

    #[test]
    fn from_str() {
        // Check normal codes
        assert_eq!(LanguageCode::from_str("eng").unwrap(), LanguageCode::Eng);
        assert_eq!(LanguageCode::from_str("deu").unwrap(), LanguageCode::Deu);
        assert_eq!(LanguageCode::from_str("jpn").unwrap(), LanguageCode::Jpn);
        
        // Check reserved range qaa-qtz is catching OK
        assert!(LanguageCode::from_str("pzz").is_err());
        assert_eq!(LanguageCode::from_str("qaa").unwrap(), LanguageCode::Reserved);
        assert_eq!(LanguageCode::from_str("qtz").unwrap(), LanguageCode::Reserved);
        assert!(LanguageCode::from_str("qua").is_err());
    }
}

// ------------------------------------------------------------------------------------------------
//
// The rest of this file is generated by the package build script.
//
// ------------------------------------------------------------------------------------------------

include!(concat!(env!("OUT_DIR"), "/part_2.rs"));
