/*!
This module provides an implementation of ISO 639-1, Codes for the
representation of names of languages — Part 1: Alpha-2 code.
 */

// ------------------------------------------------------------------------------------------------
//
// The rest of this file is generated by the package build script.
//
// ------------------------------------------------------------------------------------------------

include!(concat!(env!("OUT_DIR"), "/part_1.rs"));
