/*!
This module provides an implementation of ISO 639-5, Codes for the
representation of names of languages — Part 5: Alpha-3 code for language
families and groups.
 */

// ------------------------------------------------------------------------------------------------
//
// The rest of this file is generated by the package build script.
//
// ------------------------------------------------------------------------------------------------

include!(concat!(env!("OUT_DIR"), "/part_5.rs"));
