/*!
Codes for the representation of names of countries and their subdivisions –
Part 2: Country subdivision code, defines codes for the names of the principal
subdivisions (e.g., provinces, states, departments, regions) of all countries
coded in ISO 3166-1.

The purpose of ISO 3166-2 is to establish an international standard of short
and unique alphanumeric codes to represent the relevant administrative
divisions and dependent territories of all countries in a more convenient and
less ambiguous form than their full names. Each complete ISO 3166-2 code
consists of two parts, separated by a hyphen:

* The first part is the ISO 3166-1 alpha-2 code of the country;
* The second part is a string of up to three alphanumeric characters, which
  is usually obtained from national sources and stems from coding systems
  already in use in the country concerned, but may also be developed by the
  ISO itself.

Each complete ISO 3166-2 code can then be used to uniquely identify a country
subdivision in a global context.

# Categories

Each country defines a set of categories that describe the different entities
they recognize. For example, consider the following three records. Note that
both Australia and the USA define a code for *state*, these are distinct as
their local meaning may differ.

| Country | Name                     | Subdivisions |
| ------- | ------------------------ | ------------ |
| AU      | Australia                | 6 states, and 2 territories |
| UG      | Uganda                   | 4 geographical regions, 134 districts, and 1 city |
| US      | United States of America | 50 states, 1 district, and 6 outlying areas |

# Territories

In the example above Australia is noted as having 2 territories, and
territories may be listed in part-1 as non-independent countries. In such
cases the [SubdivisionCode] will have a `CountryCode` value named *separate
country code*.

# Example

YYYYY

*/

// ------------------------------------------------------------------------------------------------
//
// The rest of this file is generated by the package build script.
//
// ------------------------------------------------------------------------------------------------

include!(concat!(env!("OUT_DIR"), "/part_2.rs"));

// ------------------------------------------------------------------------------------------------
// Modules
// ------------------------------------------------------------------------------------------------

#[cfg(feature = "categories")]
#[doc(hidden)]
mod categories;
#[cfg(feature = "categories")]
pub use categories::{SubdivisionCategoryCode, ALL_CODES as ALL_CATEGORIES};

#[cfg(feature = "territories")]
#[doc(hidden)]
mod territories;
#[cfg(feature = "territories")]
pub use territories::{TerritoryCode, ALL_CODES as ALL_TERRITORIES};

#[cfg(feature = "indices")]
pub mod indices;
