/*!
Codes for the representation of names of countries and their subdivisions –
Part 2: Country subdivision code, defines codes for the names of the principal
subdivisions (e.g., provinces, states, departments, regions) of all countries
coded in ISO 3166-1.

The purpose of ISO 3166-2 is to establish an international standard of short
and unique alphanumeric codes to represent the relevant administrative
divisions and dependent territories of all countries in a more convenient and
less ambiguous form than their full names. Each complete ISO 3166-2 code
consists of two parts, separated by a hyphen:[1]

* The first part is the ISO 3166-1 alpha-2 code of the country;
* The second part is a string of up to three alphanumeric characters, which
  is usually obtained from national sources and stems from coding systems
  already in use in the country concerned, but may also be developed by the
  ISO itself.

Each complete ISO 3166-2 code can then be used to uniquely identify a country
subdivision in a global context.

# Categories

# Territories

# Example

YYYYY

*/

// ------------------------------------------------------------------------------------------------
//
// The rest of this file is generated by the package build script.
//
// ------------------------------------------------------------------------------------------------

include!(concat!(env!("OUT_DIR"), "/part_2.rs"));

// ------------------------------------------------------------------------------------------------
// Modules
// ------------------------------------------------------------------------------------------------

#[cfg(feature = "categories")]
#[doc(hidden)]
mod categories;
#[cfg(feature = "categories")]
pub use categories::SubdivisionCategoryCode;

#[cfg(feature = "territories")]
#[doc(hidden)]
mod territories;
#[cfg(feature = "territories")]
pub use territories::TerritoryCode;
